### PR TITLE
Make compilation using cmake works

### LINKED ISSUE #168: Undefined symbols when build with CMake
Step to reproduce:

```
rm -rf build
mkdir -p build
cd build
cmake -DCMAKE_PREFIX_PATH=$HOME/src/github.com/wingyplus/jeab/.deps ..
make
```

It's show compilation fail below:

```
Undefined symbols for architecture x86_64:
  "_IMG_InitJPG", referenced from:
      _IMG_Init in IMG.c.o
  "_IMG_InitPNG", referenced from:
      _IMG_Init in IMG.c.o
  "_IMG_InitTIF", referenced from:
      _IMG_Init in IMG.c.o
  "_IMG_Load", referenced from:
      _IMG_LoadTexture in IMG.c.o
     (maybe you meant: _IMG_LoadXXX_RW, _IMG_LoadICO_RW , _IMG_LoadLBM_RW , _IMG_LoadTexture , _IMG_LoadGIFAnimation_RW , _IMG_LoadBMP_RW , _IMG_LoadGIF_RW_Internal , _IMG_LoadPNM_RW , _IMG_LoadAnimationTyped_RW , _IMG_LoadTextureTyped_RW , _IMG_LoadXV_RW , _IMG_LoadTexture_RW , _IMG_LoadWEBP_RW , _IMG_LoadAnimation , _IMG_LoadTyped_RW , _IMG_LoadPCX_RW , _IMG_LoadAnimation_RW , _IMG_LoadSVG_RW , _IMG_LoadCUR_RW , _IMG_LoadXPM_RW , _IMG_LoadXCF_RW , _IMG_Load_RW )
  "_IMG_LoadGIF_RW", referenced from:
      _supported in IMG.c.o
     (maybe you meant: _IMG_LoadGIF_RW_Internal)
  "_IMG_LoadJPG_RW", referenced from:
      _supported in IMG.c.o
  "_IMG_LoadPNG_RW", referenced from:
      _supported in IMG.c.o
  "_IMG_LoadTGA_RW", referenced from:
      _supported in IMG.c.o
  "_IMG_LoadTIF_RW", referenced from:
      _supported in IMG.c.o
  "_IMG_QuitJPG", referenced from:
      _IMG_Quit in IMG.c.o
  "_IMG_QuitPNG", referenced from:
      _IMG_Quit in IMG.c.o
  "_IMG_QuitTIF", referenced from:
      _IMG_Quit in IMG.c.o
  "_IMG_isGIF", referenced from:
      _supported in IMG.c.o
      _supported_anims in IMG.c.o
  "_IMG_isJPG", referenced from:
      _supported in IMG.c.o
  "_IMG_isPNG", referenced from:
      _supported in IMG.c.o
  "_IMG_isTIF", referenced from:
      _supported in IMG.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libSDL2_image.dylib] Error 1
make[1]: *** [CMakeFiles/SDL2_image.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by wingyplus**
Add SDL_IMAGE_USE_COMMON_BACKEND to make compilation using cmake works.

Fixes #168

### CODE REVIEW

**Comment by sezero** [comment]
Failure in #168 is because the cmake script doesn't know anything about
ImageIO option:  This needs more work to support ImageIO as an option
under mac (or ios), and define `SDL_IMAGE_USE_COMMON_BACKEND` only if
ImageIO is specifically disabled. See configure.in for it.

**Comment by wingyplus** [comment]
Thanks for your suggestion. I'll take a look at the weekend. :)

**Comment by sezero** [comment]
This should be fixed by https://github.com/libsdl-org/SDL_image/pull/174 (https://github.com/libsdl-org/SDL_image/commit/2da280d5ccd2289707a428c416533331045efe4e)
