### ISSUE TITLE
Visual Studio 2026: Unresolved external symbol IMG_LoadTexture_IO referenced in function SDL_AppInit

### ISSUE THREAD

**Issue by cmyerstpsbw-source** [libsdl-org/SDL_image#680]
I'm not able to build the Hello program to be able to add SDL3_image to my main project.

**Comment by slouken** [comment]
Does it work with the 3.4.0 release?
